apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: incidentpilot
  namespace: argocd
  finalizers: [resources-finalizer.argocd.argoproj.io]
  annotations: {argocd.argoproj.io/sync-wave: "1"}
spec:
  project: default
  source:
    repoURL: git@github.com:YASHMAHAKAL/incident-pilot.git
    targetRevision: main
    path: deploy/helm/incidentpilot
  destination:
    server: https://kubernetes.default.svc
    namespace: incidentpilot-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions: [CreateNamespace=true, PruneLast=true]
